using Core.Application.Mappings;
using Core.Application.Models;
using Core.Application.Interfaces;
using MediatR;
using MediatR.Wrappers;
using ProtoBuf;
using ProtoBuf.Meta;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;

namespace Services.ProductsService.Protos
{
    public static class Protogen
    {
        public static void Generate() 
        {
            var assembly = Assembly.GetAssembly(typeof(Program));

            var requestTypes = assembly.GetTypes().Where(p => p.GetInterfaces()
                .Any(i => (i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IRequest<>))));     
            var responseTypes = assembly.GetTypes().Where(p => p.GetInterfaces().Any(i => i == typeof(IResponse)));       
            
            var method = typeof(Serializer).GetMethods().FirstOrDefault(p => p.IsGenericMethod && p.IsPublic && p.IsStatic && p.Name == "GetProto")
                ?? throw new ArgumentNullException("GetProto");

            var service = assembly.GetTypes().Single(p => p.IsSubclassOf(typeof(DaprBaseService)));

            var builder = new StringBuilder();
            builder.AppendLine("// This file has been generated by Protogen.cs");
            builder.AppendLine();

            builder.AppendLine("syntax = \"proto3\";");
            builder.AppendLine($"option csharp_namespace = \"Services.{service.Name}.Generated\";");      
            builder.AppendLine();

            builder.AppendLine("// Requests");
            foreach (var type in requestTypes)
            {
                var genericMethod = method.MakeGenericMethod(type);
                var protoOutput = genericMethod.Invoke(null, Array.Empty<object>()) 
                    ?? throw new InvalidOperationException("Cannot invoke GetProto method."); 
                var protoStr = protoOutput.ToString();
                protoStr = protoStr?.Substring(protoStr.IndexOf("message")) ?? "";

                protoStr = Regex.Replace(protoStr, @"(message \w*)(Command|Query)( {.*)", @"$1Request$3");

                builder.Append(protoStr);
            }
            builder.AppendLine();

            builder.AppendLine("// Responses");
            foreach (var type in responseTypes)
            {
                var genericMethod = method.MakeGenericMethod(type);
                var protoOutput = genericMethod.Invoke(null, Array.Empty<object>()) 
                    ?? throw new InvalidOperationException("Cannot invoke GetProto method."); 
                var protoStr = protoOutput.ToString();
                protoStr = protoStr?.Substring(protoStr.IndexOf("message")) ?? "";

                protoStr = Regex.Replace(protoStr, @"(message \w*)(Dto)( {.*)", @"$1Response$3");

                builder.Append(protoStr);
            }

            var result = builder.ToString();

            string path = Path.Combine("Protos", $"{service.Name}.proto");
            File.WriteAllText(path, result);
        }
    }
}
