// This file has been generated by Core.Application.Helpers/Protogen.cs
using AutoMapper;
using Services.ProductsService.Generated;
using Services.ProductsService.Application.Queries;
using Services.ProductsService.Application.Commands;
using Core.Domain.Entities;

namespace Services.ProductsService.Protos;

public class GrpcProfile : Profile
{
	public GrpcProfile()
	{
		CreateMap<GetProductByIdRequest,GetProductByIdQuery>();
		CreateMap<GetProductsRequest,GetProductsQuery>();
		CreateMap<CreateProductRequest,CreateProductCommand>();
		CreateMap<DeleteProductRequest,DeleteProductCommand>();
		CreateMap<PerformanceTestRequest,PerformanceTestCommand>();
		CreateMap<UpdateProductRequest,UpdateProductCommand>();
		CreateMap<PerformanceTestDto,PerformanceTestResponse>();
		CreateMap<GetProductByIdDto,GetProductByIdResponse>();
	}
}